WiRED-International/wired_modules_api

- .gitignore
- config/connection.js
- controllers/index.js
- models/index.js
- models/modules.js
- models/reference.js
- package.json
- server.js
This PR is the initial setup of the server, mysql, sequelize, and two models.
> initial setup

- controllers/api/categoriesRoutes.js
- controllers/api/index.js
- controllers/api/moduleSubCategoryRoutes.js
- controllers/api/modulesRoutes.js
- controllers/api/subCategoriesRoutes.js
- models/categories.js
- models/index.js
- models/modules.js
- models/subCategories.js
- server.js
This PR adds API end routes for the health modules.
> routes setup

- controllers/api/subCategoriesRoutes.js
This PR edits the subcategoriesRoutes to match the modules table.
> edit subcategories

- models/subCategories.js
This PR makes a slight change to the timestamp  in the subcategories table.
> debug subcategories

- controllers/api/authRoutes.js
- controllers/api/index.js
- controllers/api/userRoutes.js
- controllers/index.js
- middleware/auth.js
- middleware/isAdmin.js
- models/index.js
- models/users.js
- package.json
- server.js
This PR adds a user table, auth routes, user routes, and middleware to handle user registration and login.
> start registration

- config/connection.js
- controllers/api/authRoutes.js
- controllers/api/citiesRoutes.js
- controllers/api/countriesRoutes.js
- controllers/api/index.js
- controllers/api/modulesRoutes.js
- controllers/api/organizationsRoutes.js
- controllers/api/userRoutes.js
- middleware/isAdmin.js
- models/admins.js
- models/cities.js
- models/countries.js
- models/index.js
- models/modules.js
- models/organizations.js
- models/users.js
- seeds/cities-seeds.js
- seeds/countries-seeds.js
- seeds/index.js
- seeds/organizations-seeds.js
This PR adds more tables to prepare for CHWs to register and login to the CME tracker.
> add CME tables and routes

- controllers/api/userRoutes/authRoutes.js
- controllers/api/userRoutes/countriesRoutes.js
This PR makes changes to the auth routes and countrires routes, so that users can select from a list of countries during registration and the country gets properly created in the database.
> updated auth routes to include countries during registration

- controllers/api/userRoutes/authRoutes.js
- middleware/auth.js
- seeds/modules-seeds.js
- server.js
This PR adds a route to renew the user's token.
> renew token

- migrations/20250203092824-countries.js
- migrations/20250203094504-roles.js
- migrations/20250203094757-users.js
This PR makes slight adjustments to the migration files.
> fix migrations

- migrations/20250203074950-cme-tracker.js
- migrations/20250203082921-admin-permissions.js
- migrations/20250203094757-users.js
- models/moduleModels/quizScores.js
- models/userModels/adminPermissions.js
- models/userModels/cities.js
- models/userModels/organizations.js
- models/userModels/users.js
This PR makes edits to model references.
> edit model references

- models/moduleModels/modules.js
This PR adds the redirect back to the modules model.
> add redirect modules back to model

- server.js
This  PR adds dotenv to server,js.
> add dotenv to server.js

- controllers/api/userRoutes/authRoutes.js
- middleware/auth.js
- server.js
This PR removes all the token renewal code.
> remove token renewal

- controllers/api/moduleRoutes/downloadsRoutes.js
- seeds/packages-seeds.js
updated downloads routes file to perform necessary filtering and sorting
> Download filter and sort

- controllers/api/moduleRoutes/modulesRoutes.js
- controllers/api/moduleRoutes/packagesRoutes.js
- models/moduleModels/downloads.js
- package.json
- seeds/downloads-seeds-data.js
- seeds/downloads-seeds.js
Updated downloads seeds
created routes for just querying download names and ids
> updates for google map accomadation

- controllers/api/index.js
- controllers/api/moduleRoutes/leaderboard.js
- seeds/quizScores-seeds.js
- server.js
This PR adds a leaderboard route that sorts users by completed quizzes and an average of scores.
> create leaderboard route

- controllers/api/userRoutes/userRoutes.js
This PR adds a user delete route that allows a user to delete their own account.
> add delete route

- migrations/20250315205848-add-code-to-countries.js
This PR edits the "add code to countries" migrations file.
> edit countries code migration

- controllers/api/moduleRoutes/quizScoreRoutes.js
- controllers/api/userRoutes/userRoutes.js
The PR moves the countries model under users instead of quiz scores to fix login issues.
> countries under user

- controllers/api/index.js
This PR remove api from two routes.
> change api

- migrations/20250513070826-user-specializations-pivot-table.js
- models/index.js
- package.json
- seeds/index.js
- seeds/pivot-seed.js
- seeds/user-specializations-seeds.js
- server.js
This PR makes edits to the userSpecialization pivot table seeds and migration file.
> adjust user specialization table

- controllers/api/userRoutes/userRoutes.js
- seeds/quizScores-seeds.js
- seeds/specializations-seeds.js
- seeds/user-specializations-seeds.js
- seeds/users-seeds.js
added route for a broad search that combines first_name, last_name, and email
> User seeds

- controllers/api/userRoutes/countriesRoutes.js
- controllers/api/userRoutes/userRoutes.js
I left the old code with the problematic query commented out, with comments explaining why, in case we ever wanted to use it again
> Manual user sorting

- controllers/api/moduleRoutes/modulesRoutes.js
- migrations/20251004073215-add-type-to-modules.js
- models/moduleModels/modules.js
This PR adds a new "type" column for the modules table.
> add type column to modules table
